In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [12]:
nsw_statistics = pd.read_csv("/Users/waqarmohiuddin/Library/Mobile Documents/com~apple~Numbers/Documents/NSW_trends.csv")

In [ ]:
nsw_statistics

                                                                                                                                                                                                                                           Table 1
Offence type                              Jul 2015 - Jun 2016 Jul 2016 - Jun 2017 Jul 2017 - Jun 2018 Jul 2018 - Jun 2019 Jul 2019 - Jun 2020 Jul 2020 - Jun 2021 Jul 2021 - Jun 2022 Jul 2022 - Jun 2023 Jul 2023 - Jun 2024  Jul 2024 - Jun 2025
Murder *                                  60                  71                  54                  79                  72                  58                  65                  54                  74                                    75
Attempted murder                          24                  21                  16                  23                  28                  28                  14                  8                   14                                    17
Murder accessory, conspiracy              5                   3                   3                   2                   1                   0                   1                   1                   4                                      1
Manslaughter *                            9                   8                   11                  12                  10                  2                   6                   11                  15                                     9
...                                                                                                                                                                                                                                            ...
Fail to appear                            751                 701                 531                 496                 704                 789                 910                 866                 710                                  157
Resist or hinder officer                  6,459               6,188               6,270               6,074               5,860               5,505               5,713               5,544               5,295                              5,804
Other offences against justice procedures 569                 631                 566                 1,100               1,845               1,898               2,060               2,635               2,253                              2,087
Transport regulatory offences             113,037             130,222             123,858             109,235             99,537              74,549              64,944              71,891              65,976                            58,335
Other offences                            15,516              15,008              15,413              14,683              22,186              29,330              89,779              14,649              12,441                            11,628

[63 rows x 1 columns]

In [15]:
nsw_statistics = nsw_statistics.set_index(nsw_statistics.columns[0])

In [16]:
nsw_statistics

Empty DataFrame
Columns: []
Index: [Jul 2024 - Jun 2025, 75, 17, 1, 9, 38,169, 34,325, 2,655, 12,337, 8,709, 233, 1,017, 95, 721, 1,128, 297, 48,706, 1,515, 18,316, 8,146, 7,574, 14,825, 25,314, 29,552, 15,718, 1,896, 238, 40,073, 20,291, 4,378, 47,082, 1,894, 1,393, 12,288, 7,863, 865, 4,730, 993, 249, 526, 1,533, 248, 317, 467, 56, 61, 4,663, 14,830, 12,978, 2,865, 838, 2,965, 19, 5,263, 1,254, 150, 26,692, 56,759, 157, 5,804, 2,087, 58,335, 11,628]

[63 rows x 0 columns]